name: Golang
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install Dependencies
        run: |
          go version
          go install golang.org/x/lint/golint@latest
      - name: Run Build
        run: go build .
      - name: Run vet and lint
        run: |
          go vet .
          golint .
      #- name: Run Tests
      #  run: go test -cover ./...
